SELECT
    AFIH.WARPL AS "Maintenance Plan",
    AUFK.AUART AS "Order Type",
    AFIH.AUFNR AS "Work Order",
    AUFK.VAPLZ AS "Work Center",
    AFVC.VORNR AS "Operation Number",
    op.ARBPL AS "Op Work Center",
    AFVC.ANZZL AS "Planned Capacity"
    ,AFVV.DAUNO AS "Planned Work"
    ,ltrim(AFVC.RMZHL,'0') AS "Actual Capacity"
    ,AFVV.ISMNW AS "Actual Work"
    ,CASE AFKO.GSTRP WHEN '00000000' THEN NULL WHEN ' ' THEN NULL WHEN NULL THEN NULL ELSE TO_CHAR(TO_DATE(AFKO.GSTRP, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Basic Start Date"
    ,CASE AFKO.GETRI WHEN '00000000' THEN NULL WHEN ' ' THEN NULL WHEN NULL THEN NULL ELSE TO_CHAR(TO_DATE(AFKO.GETRI, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Confirmed Finish Date"

    FROM AFIH

    JOIN AFKO ON AFKO.AUFNR = AFIH.AUFNR
    JOIN AUFK ON AUFK.AUFNR = AFIH.AUFNR
    JOIN AFVC ON AFVC.AUFPL = AFKO.AUFPL
    JOIN AFVV ON AFVV.AUFPL = AFVC.AUFPL AND AFVV.APLZL = AFVC.APLZL
    --FULL OUTER JOIN EQKT ON EQKT.EQUNR = AFIH.EQUNR
    FULL OUTER JOIN ILOA ON ILOA.ILOAN = AFIH.ILOAN
    JOIN IFLOTX ON IFLOTX.TPLNR = ILOA.TPLNR
    LEFT JOIN CRHD op ON op.OBJID = AFVC.ARBID
    
    WHERE AFKO.GETRI = '20181002'
    AND AUFK.AUART IN ('8F02')
    AND op.ARBPL = 'MIC_P'
    
    ORDER BY AFIH.AUFNR
    ;