SELECT
	AUFK.AUFNR AS "Order"
    ,CASE AUFK.AUART 
        WHEN '8F01' THEN 'CM'
        WHEN '8F02' THEN 'PM'
        WHEN '8F03' THEN 'ST'
        WHEN '8F06' THEN 'OPS'
        END
        AS "Order Type"
        
    ,AFIH.PRIOK AS "Priority"
    --,AFIH.ILART AS "Activity Type"
    ,ILOA.EQFNR AS "Tag"
    ,ILOA.ABCKZ AS "ABC"
    ,AUFK.KTEXT AS "Order Description"
    ,(
        SELECT
			LISTAGG(TJ30T.TXT04, ' ') WITHIN GROUP (ORDER BY TJ30T.TXT04)
		FROM JEST
		JOIN JSTO ON JSTO.OBJNR = JEST.OBJNR
		JOIN TJ30T ON JSTO.STSMA = TJ30T.STSMA AND JEST.STAT = TJ30T.ESTAT
		WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ30T.SPRAS = 'E'
    ) AS "User Status"
    ,(
        SELECT
			LISTAGG(TJ02T.TXT04, ' ') WITHIN GROUP (ORDER BY TJ02T.TXT04)
		FROM JEST
		JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
		WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
    ) AS "System Status"
    
    --,AUFK.OBJNR AS "Object"
    ,CASE AFKO.GLTRP WHEN '00000000' THEN NULL ELSE TO_CHAR(TO_DATE(AFKO.GLTRP, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Basic Finish Date"
    ,CASE CRHD.ARBPL
            WHEN 'TAB_P' THEN 'FMT'
            WHEN 'FMG_P' THEN 'FMT'
            WHEN 'MIC_P' THEN 'CMT'
            WHEN 'IC' THEN 'IC'
            WHEN 'WTR_P' THEN 'WWT/WTR'
            WHEN 'ELEC_P' THEN 'ELEC'
            WHEN 'GAS_P' THEN 'GAS'
            WHEN 'CHEM_P' THEN 'CHEM'
            WHEN 'SLUR_P' THEN 'SLURRY'
            WHEN 'ALOP_P' THEN 'AL OP'
            WHEN 'BS' THEN 'BS'
            WHEN 'TGM' THEN 'TGM'
            ELSE CRHD.ARBPL
        END AS "Work Center"
    --,CRHD.ARBPL
    --,CASE AFKO.GETRI WHEN '00000000' THEN NULL ELSE TO_CHAR(TO_DATE(AFKO.GETRI, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Confirmed Finish Date"
    ,CASE AUFK.ZZ_COMPLSTART_DATE WHEN '00000000' THEN NULL ELSE TO_CHAR(TO_DATE(AUFK.ZZ_COMPLSTART_DATE , 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Compliance Start"
    ,CASE AUFK.ZZ_COMPLEND_DATE WHEN '00000000' THEN NULL ELSE TO_CHAR(TO_DATE(AUFK.ZZ_COMPLEND_DATE, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Compliance End"
    ,FLOOR(SYSDATE - TO_DATE(AUFK.ERDAT, 'YYYYMMDD')) AS "Days Open"
    ,CASE AFKO.GLTRP WHEN '00000000' THEN FLOOR(SYSDATE - TO_DATE(AUFK.ERDAT, 'YYYYMMDD')) ELSE FLOOR(SYSDATE - TO_DATE(AFKO.GLTRP, 'YYYYMMDD')) END AS "Overdue Days"
    ,CASE AFIH.PRIOK WHEN '4' THEN '1' WHEN '3' THEN '2' WHEN '3' THEN '2' WHEN '1' THEN '4' ELSE '2' END AS "P Score"
    ,CASE ILOA.ABCKZ WHEN 'A' THEN '6' WHEN 'B' THEN '5' WHEN 'C' THEN '4' WHEN 'D' THEN '3' WHEN 'E' THEN '2' WHEN 'F' THEN '1' ELSE NULL END AS "A Score"
    ,CASE AFIH.PRIOK WHEN '4' THEN '1' WHEN '3' THEN '2' WHEN '3' THEN '2' WHEN '1' THEN '4' ELSE '2' END 
    *
    CASE ILOA.ABCKZ WHEN 'A' THEN '6' WHEN 'B' THEN '5' WHEN 'C' THEN '4' WHEN 'D' THEN '3' WHEN 'E' THEN '2' WHEN 'F' THEN '1' ELSE NULL END AS "R Score"
    ,(
        SELECT
			LISTAGG(PA0002.VNAMC || ' ' || PA0002.NCHMC, ', ') WITHIN GROUP (ORDER BY IHPA.PARNR)
		FROM IHPA
        LEFT JOIN PA0002 ON PA0002.PERNR = IHPA.PARNR AND PA0002.ENDDA = '99991231'
		WHERE IHPA.OBJNR = AUFK.OBJNR
    ) AS "Responsible"
    , (
    SELECT
        SUM(AFVV.DAUNO)
        FROM AFVC
        JOIN AFVV ON AFVV.AUFPL = AFVC.AUFPL AND AFVV.APLZL = AFVC.APLZL
        WHERE AFVC.AUFPL = AFKO.AUFPL
    ) AS "Planned Work"
    , (
    SELECT
        SUM(AFVV.ISMNW)
        FROM AFVC
        JOIN AFVV ON AFVV.AUFPL = AFVC.AUFPL AND AFVV.APLZL = AFVC.APLZL
        WHERE AFVC.AUFPL = AFKO.AUFPL
    ) AS "Actual Work"
    
FROM AUFK
JOIN AFIH ON AFIH.AUFNR = AUFK.AUFNR
JOIN AFKO ON AFKO.AUFNR = AFIH.AUFNR
JOIN CRHD ON CRHD.OBJID = AFIH.GEWRK
JOIN ILOA ON ILOA.ILOAN = AFIH.ILOAN

WHERE 
AUFK.AUART NOT IN ('8O01') AND AUFK.LOEKZ != 'X'
--AND (AFKO.GLTRP < '20190225' OR AFKO.GLTRP IS NULL)
AND AUFK.AUART IN ('8F01', '8F02', '8F03', '8F06')
/*
System status selection
*/
AND 
(
    
    NOT EXISTS (
        SELECT TJ02T.TXT04
        FROM JEST
        JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
        WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
        AND TJ02T.TXT04 IN ('DLFL', 'CNF', 'TECO', 'CLSD')
    )
    /*
    AND
    EXISTS (
        SELECT TJ02T.TXT04
        FROM JEST
        JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
        WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
        AND TJ02T.TXT04 IN ('REL')
    )
    */
)

/*
User status selection
*/

AND 
(
    
    NOT EXISTS (
        SELECT TJ30T.TXT04
        FROM JEST
        JOIN JSTO ON JSTO.OBJNR = JEST.OBJNR
		JOIN TJ30T ON JSTO.STSMA = TJ30T.STSMA AND JEST.STAT = TJ30T.ESTAT
		WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ30T.SPRAS = 'E'
        AND TJ30T.TXT04 IN ('CNCL')
    )
    /*
    AND
    EXISTS (
        SELECT TJ30T.TXT04
        FROM JEST
        JOIN JSTO ON JSTO.OBJNR = JEST.OBJNR
		JOIN TJ30T ON JSTO.STSMA = TJ30T.STSMA AND JEST.STAT = TJ30T.ESTAT
		WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ30T.SPRAS = 'E'
        AND TJ30T.TXT04 IN ('HOLD')
    )
    */
    
)
--GROUP BY "Order", "Order Type", "Priority", "Activity Type"

--GROUP BY AUFK.AUFNR, AUFK.AUART, AFIH.PRIOK, AFIH.ILART, ILOA.EQFNR, ILOA.ABCKZ, AUFK.KTEXT, "User Status", "System Status", AUFK.OBJNR, AFKO.GLTRP, CRHD.ARBPL, AFKO.GETRI, 
--AUFK.ZZ_COMPLSTART_DATE, AUFK.ZZ_COMPLEND_DATE, AUFK.ERDAT, AFKO.GLTRP, AFIH.PRIOK, ILOA.ABCKZ, "R Score", "partners", "planned_work"
;