SELECT
    AFIH.IWERK AS "plant"
    ,AFIH.AUFNR AS "order"
    ,AUFK.AUART AS "order_type"
    ,AFIH.PRIOK AS "priority"
    --,ILOA.ABCKZ AS "abc"
    ,AUFK.KTEXT AS "order_description"
    ,AFIH.EQUNR AS "equipment"
    ,AUFK.VAPLZ AS "work_center"
    ,CRHD.ARBPL AS "op_work_center"
    ,MAX(AFVV.DAUNO) OVER (PARTITION BY AFIH.AUFNR || CRHD.ARBPL) AS "duration"
    ,SUM(AFVV.ISMNW) OVER (PARTITION BY AFIH.AUFNR) AS "actual_work"
    ,A."cycle"
    ,CASE WHEN A."cycle" <= 7 THEN 3 ELSE CEIL(A."cycle" * .1) END AS "window"
    ,CASE WHEN A.NPLDA != '00000000' THEN to_number(to_char(to_date(A.NPLDA ,'YYYYMMDD') - CASE WHEN A."cycle" <= 7 THEN 3 ELSE CEIL(A."cycle" * .1) END, 'YYYYMMDD')) ELSE NULL END AS "window_start"
    ,to_number(A.NPLDA) AS "planned_date"
    ,CASE WHEN A.NPLDA != '00000000' THEN to_number(to_char(to_date(A.NPLDA ,'YYYYMMDD') + CASE WHEN A."cycle" <= 7 THEN 3 ELSE CEIL(A."cycle" * .1) END, 'YYYYMMDD')) ELSE NULL END AS "window_end"
    ,AFKO.GSTRP AS "basic_start_date"
    ,AFKO.GLTRP AS "basic_finish_date"
    ,AFKO.GETRI AS "confirmed_finish_date"
    , (
        SELECT
			LISTAGG(TJ30T.TXT04, ' ') WITHIN GROUP (ORDER BY TJ30T.TXT04)
		FROM JEST
		JOIN JSTO ON JSTO.OBJNR = JEST.OBJNR
		JOIN TJ30T ON JSTO.STSMA = TJ30T.STSMA AND JEST.STAT = TJ30T.ESTAT
		WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ30T.SPRAS = 'E'
    ) AS "user_status"
    ,(
        SELECT
			LISTAGG(TJ02T.TXT04, ' ') WITHIN GROUP (ORDER BY TJ02T.TXT04)
		FROM JEST
		JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
		WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
    ) AS "system_status"
    ,AUFK.ZZ_COMPLSTART_DATE AS "compliance_start"
    ,AUFK.ZZ_COMPLEND_DATE AS "compliance_end"
    ,(
        SELECT
			LISTAGG(IHPA.PARNR, ',') WITHIN GROUP (ORDER BY IHPA.PARNR)
		FROM IHPA
		WHERE IHPA.OBJNR = AUFK.OBJNR
    ) AS "partners"
    
FROM AFIH

JOIN AFKO ON AFKO.AUFNR = AFIH.AUFNR
JOIN AUFK ON AUFK.AUFNR = AFIH.AUFNR
JOIN AFVC ON AFVC.AUFPL = AFKO.AUFPL
JOIN AFVV ON AFVV.AUFPL = AFVC.AUFPL AND AFVV.APLZL = AFVC.APLZL
JOIN CRHD ON CRHD.OBJID = AFVC.ARBID
--FULL OUTER JOIN EQKT ON EQKT.EQUNR = AFIH.EQUNR
--FULL OUTER JOIN EQUZ ON EQUZ.EQUNR = AFIH.EQUNR
--FULL OUTER JOIN ILOA ON ILOA.ILOAN = EQUZ.ILOAN
--JOIN IFLOTX ON IFLOTX.TPLNR = ILOA.TPLNR
FULL OUTER JOIN (
    SELECT
        WARPL
        ,NPLDA
        ,ABNUM
        ,MAX(ROUND(ZYKZT / 3600 / 24, 2)) AS "cycle"
    FROM MHIS
    GROUP BY WARPL, NPLDA, ABNUM
) A ON A.WARPL = AFIH.WARPL AND A.ABNUM = AFIH.ABNUM

WHERE AFIH.IWERK = '8000'
AND AUFK.AUART IN ('8F06', '8F03', '8F02', '8F01')
AND (AFKO.GETRI || AFKO.GEUZI >= '20181101000000' AND AFKO.GETRI <= '20190131')
;