SELECT
    CABN.ATINN AS "primary"
    ,KSML.IMERK AS "key"
    ,KLAH.CLASS AS "classification"
    ,CABNT.ATBEZ AS "description"
    ,CAWN.ATWRT AS "options"
    ,CABN.ATFOR AS "type"
    ,CABN.ANZST AS "limit"
    ,CABN.ATEIN AS "single"
    ,CABN.ATERF AS "required"
    ,CABN.ATSCH AS "template"
    ,CAWN.ATSTD AS "default"
    
FROM KLAH
JOIN KSML ON KSML.CLINT = KLAH.CLINT
FULL OUTER JOIN CABNT ON CABNT.ATINN = KSML.IMERK AND CABNT.SPRAS = 'E'
FULL OUTER JOIN CAWN ON CAWN.ATINN = CABNT.ATINN
JOIN CABN ON CABN.ATINN = CABNT.ATINN
--JOIN CAWN ON CAWN.ATINN = CABN.ATINN AND CAWN.ADZHL = CABN.ADZHL

WHERE (KLAH.KLART = '002')

ORDER BY KLAH.CLASS
;