SELECT 
    EQUI.EQUNR AS "equipment"
    --,EQUZ.HEQUI AS "superior"
    ,EQUI.EQART AS "type"
    ,ILOA.EQFNR AS "tag"
    ,CRHD.ARBPL AS "work_center"
    ,EQKT.EQKTX AS "description"
    ,ILOA.ABCKZ AS "abc"
    ,ILOA.TPLNR AS "floc"
    ,IFLOTX.PLTXT AS "system"
    --,EQUI.OBJNR AS "obj"
    
    ,(
        SELECT
            LISTAGG(TJ30T.TXT04, ' ') WITHIN GROUP (ORDER BY TJ30T.TXT04)
        FROM JEST
        JOIN JSTO ON JSTO.OBJNR = JEST.OBJNR
        JOIN TJ30T ON JSTO.STSMA = TJ30T.STSMA AND JEST.STAT = TJ30T.ESTAT
        WHERE JEST.OBJNR = EQUI.OBJNR AND JEST.INACT != 'X' AND TJ30T.SPRAS = 'E'
    ) AS "user_status"
    ,(
        SELECT
            LISTAGG(TJ02T.TXT04, ' ') WITHIN GROUP (ORDER BY TJ02T.TXT04)
        FROM JEST
        JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
        WHERE JEST.OBJNR = EQUI.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
    ) AS "system_status"
    ,ILOA.SWERK
    , (
        SELECT
			LISTAGG(AFIH.AUFNR, ' ') WITHIN GROUP (ORDER BY AFIH.AUFNR)
		FROM AFIH
        JOIN AUFK ON AUFK.AUFNR = AFIH.AUFNR
		WHERE AFIH.EQUNR = EQUI.EQUNR
        AND 
(
    EXISTS (
        SELECT TJ02T.TXT04
        FROM JEST
        JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
        WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
        AND TJ02T.TXT04 IN ('NEW', 'REL')
    )
)
AND 
(
    NOT EXISTS (
        SELECT TJ02T.TXT04
        FROM JEST
        JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
        WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
        AND TJ02T.TXT04 IN ('CNF', 'TECO')
    )
)
    ) AS "open_orders"
    
FROM EQUI

JOIN EQUZ ON EQUZ.EQUNR = EQUI.EQUNR AND EQUZ.MANDT = EQUI.MANDT AND EQUZ.DATBI = '99991231'
JOIN EQKT ON EQKT.EQUNR = EQUI.EQUNR
JOIN ILOA ON ILOA.ILOAN = EQUZ.ILOAN
JOIN IFLOTX ON IFLOTX.TPLNR = ILOA.TPLNR
JOIN CRHD ON CRHD.OBJID = EQUZ.GEWRK

WHERE EQUI.EQTYP = '8' AND EQUI.MANDT = '210' AND ILOA.SWERK = '8000'
--AND CRHD.ARBPL = 'FMG_P'
--AND ILOA.ABCKZ = 'D'
--AND ILOA.TPLNR = '81F-A1-FIRE'
--AND REGEXP_LIKE(ILOA.TPLNR, '^[a-zA-Z0-9]{3}-[a-zA-Z0-9]{2}-[a-zA-Z0-9]{4}$')
AND 
(
    NOT EXISTS (
        SELECT TJ02T.TXT04
        FROM JEST
        JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
        WHERE JEST.OBJNR = EQUI.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
        AND TJ02T.TXT04 IN ('DLFL', 'INAC')
    )
)

AND 
(
    EXISTS (
        SELECT TJ02T.TXT04
        FROM JEST
        JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
        WHERE JEST.OBJNR = EQUI.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
        AND TJ02T.TXT04 IN ('INST', 'AVLB', 'ASEQ')
    )
)
AND 
(
    EXISTS (
        SELECT
            TJ30T.TXT04
        FROM JEST
        JOIN JSTO ON JSTO.OBJNR = JEST.OBJNR
        JOIN TJ30T ON JSTO.STSMA = TJ30T.STSMA AND JEST.STAT = TJ30T.ESTAT
        WHERE JEST.OBJNR = EQUI.OBJNR AND JEST.INACT != 'X' AND TJ30T.SPRAS = 'E'
        AND TJ30T.TXT04 IN ('EMRG', 'LOTO', 'UAVL')
    )
)
AND CRHD.ARBPL IN ('FMG_P', 'MIC_P')
;