SELECT
    CRHD.ARBPL AS "work_center"
    ,COUNT(*) AS "total"
    ,ILOA.ABCKZ AS "abc"
FROM EQUI

JOIN EQUZ ON EQUZ.EQUNR = EQUI.EQUNR AND EQUZ.MANDT = EQUI.MANDT AND EQUZ.DATBI = '99991231'
JOIN EQKT ON EQKT.EQUNR = EQUI.EQUNR
JOIN ILOA ON ILOA.ILOAN = EQUZ.ILOAN
JOIN IFLOTX ON IFLOTX.TPLNR = ILOA.TPLNR
JOIN CRHD ON CRHD.OBJID = EQUZ.GEWRK

WHERE EQUI.EQTYP = '8' AND ILOA.SWERK = '8000' --AND ILOA.ABCKZ IN ('A', 'B') AND EQUI.MANDT = '210'
and CRHD.ARBPL = 'ELEC_P'

AND 
(
    NOT EXISTS (
        SELECT TJ02T.TXT04
        FROM JEST
        JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
        WHERE JEST.OBJNR = EQUI.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
        AND TJ02T.TXT04 IN ('DLFL', 'INAC')
    )
)

AND 
(
    EXISTS (
        SELECT TJ02T.TXT04
        FROM JEST
        JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
        WHERE JEST.OBJNR = EQUI.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
        AND TJ02T.TXT04 IN ('INST', 'AVLB', 'ASEQ')
    )
)
--AND ILOA.ABCKZ = 'B'
GROUP BY ILOA.ABCKZ, CRHD.ARBPL ORDER BY CRHD.ARBPL
;