select 
    count(*)
FROM IFLOT

JOIN IFLOTX ON IFLOTX.TPLNR = IFLOT.TPLNR
LEFT JOIN CRHD ON CRHD.OBJID = IFLOT.LGWID
JOIN ILOA ON ILOA.ILOAN = IFLOT.ILOAN

WHERE IFLOT.MANDT = '210' AND ILOA.SWERK = '8000'
;