SELECT
    AFIH.WARPL AS "Maintenance Plan",
    AUFK.AUART AS "Order Type",
    AFIH.QMNUM AS "notification",
    AFIH.AUFNR AS "Work Order",
    AUFK.KTEXT AS "description",
    ILOA.EQFNR AS "tag_id",
    AUFK.VAPLZ AS "Work Center",
    AFVC.VORNR AS "Operation Number",
    op.ARBPL AS "Op Work Center",
    AFVC.ANZZL AS "Planned Capacity"
    ,AFVV.DAUNO AS "Planned Work"
    ,ltrim(AFVC.RMZHL,'0') AS "Acutal Capacity"
    ,AFVV.ISMNW AS "Actual Work"
    ,CASE AFKO.GSTRP WHEN '00000000' THEN NULL WHEN ' ' THEN NULL WHEN NULL THEN NULL ELSE TO_CHAR(TO_DATE(AFKO.GSTRP, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Basic Start Date"
    ,AFKO.GSUZP AS "basic_start_time"
    ,CASE AFKO.GETRI WHEN '00000000' THEN NULL WHEN ' ' THEN NULL WHEN NULL THEN NULL ELSE TO_CHAR(TO_DATE(AFKO.GETRI, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Confirmed Finish Date"
    ,AFIH.IPHAS AS "maintenance_phase" -- 0: Outstanding, 2: Released, 3: TECO, 4: Deletion Set, 5: Historical?, 6: CMPL
    
    , (
        SELECT
			LISTAGG(TJ30T.TXT04, ' ') WITHIN GROUP (ORDER BY TJ30T.TXT04)
		FROM JEST
		JOIN JSTO ON JSTO.OBJNR = JEST.OBJNR
		JOIN TJ30T ON JSTO.STSMA = TJ30T.STSMA AND JEST.STAT = TJ30T.ESTAT
		WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ30T.SPRAS = 'E'
    ) AS "user_status"
    ,(
        SELECT
			LISTAGG(TJ02T.TXT04, ' ') WITHIN GROUP (ORDER BY TJ02T.TXT04)
		FROM JEST
		JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
		WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
    ) AS "system_status"
    /*
    ,(
        SELECT
			LISTAGG(PA0002.VNAMC || ' ' || PA0002.NCHMC, ', ') WITHIN GROUP (ORDER BY IHPA.PARNR)
		FROM IHPA
        JOIN PA0002 ON PA0002.PERNR = IHPA.PARNR AND PA0002.ENDDA = '99991231'
		WHERE IHPA.OBJNR = AUFK.OBJNR
    ) AS "partners"
    */
    FROM AFIH

    JOIN AFKO ON AFKO.AUFNR = AFIH.AUFNR
    JOIN AUFK ON AUFK.AUFNR = AFIH.AUFNR
    JOIN AFVC ON AFVC.AUFPL = AFKO.AUFPL
    JOIN AFVV ON AFVV.AUFPL = AFVC.AUFPL AND AFVV.APLZL = AFVC.APLZL
    --FULL OUTER JOIN EQKT ON EQKT.EQUNR = AFIH.EQUNR
    JOIN ILOA ON ILOA.ILOAN = AFIH.ILOAN
    JOIN IFLOTX ON IFLOTX.TPLNR = ILOA.TPLNR
    LEFT JOIN CRHD op ON op.OBJID = AFVC.ARBID
    
    WHERE AFKO.GSTRP BETWEEN '20180918' and '20180918'
    --AND AFIH.IWERK = '8000'
    AND AUFK.AUART IN ('8F06','8F03','8F02','8F01')

    --AND (AFKO.GETRI = '00000000' OR AFKO.GETRI = ' ' OR AFKO.GETRI = &startDate)
    
    /*
System status selection
*/
/*
AND 
(
    
    NOT EXISTS (
        SELECT TJ02T.TXT04
        FROM JEST
        JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
        WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
        AND TJ02T.TXT04 IN ('DLFL', 'TECO', 'CLSD', 'CNF')
    )
    
    /*
    AND
    EXISTS (
        SELECT TJ02T.TXT04
        FROM JEST
        JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
        WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
        AND TJ02T.TXT04 IN ('REL')
    )
    */
--)
    
    --ORDER BY AFIH.AUFNR
    ;