select distinct
    MPOS.WARPL AS "maintenance_plan"
    ,CRHD.ARBPL AS "Work Center"
    ,MPOS.PSTXT AS "description"
    ,ILOA.EQFNR AS "sort_field"
    ,ILOA.TPLNR AS "floc"
    ,MPOS.WAPOS AS "maintenance_item"
    ,MPOS.EQUNR AS "maintenance_item_equipment"
    ,PLPO.EQUNR AS "task_list_equipment"
    ,T.EQFNR AS "task_list_sort_field"
    ,op.ARBPL AS "Op Work Center"
    ,PLPO.LTXA1 AS "operation_description"
    ,PLPO.ANZZL AS "capacity"
    ,PLPO.DAUNO AS "work"
    ,PLPO.ARBEI AS "total_work_estimate"
    ,PLPO.ARBEH AS "unit"
from MPLA
JOIN MPOS ON MPOS.WARPL = MPLA.WARPL
JOIN PLKO ON MPOS.PLNNR = PLKO.PLNNR AND MPOS.PLNAL = PLKO.PLNAL
JOIN PLAS ON PLAS.PLNNR = PLKO.PLNNR AND PLAS.PLNAL = PLKO.PLNAL AND PLAS.PLNTY = 'A' AND PLAS.LOEKZ <> 'X'
JOIN PLPO ON PLPO.PLNTY = PLAS.PLNTY AND PLPO.PLNNR = PLAS.PLNNR AND PLPO.PLNKN = PLAS.PLNKN --AND PLPO.ZAEHL = PLKO.ZAEHL
JOIN ILOA ON ILOA.ILOAN = MPOS.ILOAN
FULL OUTER JOIN EQUZ ON EQUZ.EQUNR = PLPO.EQUNR
FULL OUTER JOIN ILOA T ON T.ILOAN = EQUZ.ILOAN
LEFT JOIN CRHD ON CRHD.OBJID = MPOS.GEWRK
LEFT JOIN CRHD op ON op.OBJID = PLPO.ARBID

--where PLPO.EQUNR = '000000002000001231' OR
--MPOS.EQUNR = '000000002000001231' AND
--MPOS.IWERK = 8000
--where PLPO.EQUNR = '000000002000001455' OR
--MPOS.EQUNR = '000000002000001455'

where
MPOS.IWERK = 8000
AND 
(
    NOT EXISTS (
        SELECT TJ02T.TXT04
        FROM JEST
        JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
        WHERE JEST.OBJNR = MPLA.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
        AND TJ02T.TXT04 IN ('INAC', 'DLFL')
    )
)
;