SELECT
	MARA.MATNR AS "part_number",
    MAKT.MAKTX AS "description",
    MARD.LGORT AS "location",
    MARD.LABST AS "on_hand",
    MARD.KLABS AS "consignment",
    MARA.MEINS AS "uom",
    EINE.NETPR AS "price",
    MARC.PLIFZ AS "lead_time",
    MARA.ERSDA AS "created_on",
    LFA1.NAME1 AS "vendor",
    EINA.IDNLF AS "vendor_number"
FROM MARA

JOIN MAKT ON MAKT.MATNR = MARA.MATNR AND MAKT.SPRAS = 'E'
JOIN MARD ON MARD.MATNR = MARA.MATNR
JOIN MARC ON MARC.MATNR = MARA.MATNR AND MARC.LVORM != 'X'
LEFT JOIN EINA ON EINA.MATNR = MARA.MATNR
LEFT JOIN EINE ON EINE.INFNR = EINA.INFNR
LEFT JOIN LFA1 ON LFA1.LIFNR = EINA.LIFNR

WHERE MAKT.MATNR LIKE '%001211%'
;