SELECT
	COUNT(*) AS count  
FROM AUFK
JOIN AFIH ON AFIH.AUFNR = AUFK.AUFNR
JOIN AFKO ON AFKO.AUFNR = AFIH.AUFNR
JOIN CRHD ON CRHD.OBJID = AFIH.GEWRK
JOIN ILOA ON ILOA.ILOAN = AFIH.ILOAN

WHERE 
AUFK.AUART NOT IN ('8O01')
--AND (AFKO.GLTRP != '00000000' OR AFKO.GLTRP IS NOT NULL)
--AND TO_DATE(AFKO.GLTRP, 'YYYYMMDD') BETWEEN TO_DATE('20170907', 'YYYYMMDD') AND TO_DATE('20170907', 'YYYYMMDD')
--AND (AFKO.GLTRP >= '20170926' AND AFKO.GLTRP <= '20170926')
AND AUFK.LOEKZ != 'X'
/*
System status selection
*/
AND 
(
    NOT EXISTS (
        SELECT TJ02T.TXT04
        FROM JEST
        JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
        WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
        AND TJ02T.TXT04 IN ('DLFL')
    )
    /*
    AND
    EXISTS (
        SELECT TJ02T.TXT04
        FROM JEST
        JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
        WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
        AND TJ02T.TXT04 IN ('CRTD')
    )
    */
)
/*
User status selection
*/
AND 
(
    
    NOT EXISTS (
        SELECT TJ30T.TXT04
        FROM JEST
        JOIN JSTO ON JSTO.OBJNR = JEST.OBJNR
		JOIN TJ30T ON JSTO.STSMA = TJ30T.STSMA AND JEST.STAT = TJ30T.ESTAT
		WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ30T.SPRAS = 'E'
        AND TJ30T.TXT04 IN ('CNCL')
    )
    /*
    AND
    EXISTS (
        SELECT TJ30T.TXT04
        FROM JEST
        JOIN JSTO ON JSTO.OBJNR = JEST.OBJNR
		JOIN TJ30T ON JSTO.STSMA = TJ30T.STSMA AND JEST.STAT = TJ30T.ESTAT
		WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ30T.SPRAS = 'E'
        AND TJ30T.TXT04 IN ('HOLD')
    )
    */
)
;