SELECT
    /*
    (
        SELECT
			LISTAGG(TJ02T.TXT04, ' ') WITHIN GROUP (ORDER BY TJ02T.TXT04)
		FROM JEST
		JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
		WHERE JEST.OBJNR = MPLA.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
        --AND TJ02T.TXT04 NOT IN ('DLFL', 'CNF', 'CLSD')
    ) AS "Status",
    */
    MHIS.WARPL AS "Maintenance Plan",
    MPOS.AUART AS "Order Type",
    MPLA.STRAT,
    PLPO.PLNTY,
    ROUND(MHIS.ZYKZT / 3600 / 24, 2) AS Cycle,
    AFIH.AUFNR AS "Work Order",
    MPLA.HORIZ AS Horizon,
    MHIS.NPLDA AS "Planned Date",
    MHIS.HORDA AS "Call Date",
    AFKO.GSTRP AS "Basic Start Date",
    AFKO.GLTRP AS "Basic Finish Date",
    AFKO.GETRI AS "Confirmed Finish Date",
    MPLA.CALL_CONFIRM AS "Completion Required",
    MPOS.NO_AUFRELKZ AS "No Auto Release",
    MPLA.ABRHO AS "Scheduling Period",
    CASE WHEN MPLA.HUNIT = '10' THEN 'Days' ELSE 'Years' END AS "Scheduling Period Unit",
    MPLA.WPTXT AS "Maintenance Plan Text",
    MPOS.PSTXT AS "Maintenance Item Text",
    MPLA.STRAT AS "Maintenance Strategy",
    MHIS.ZAEHL AS "Forecast Package",
    PLPO.LOEKZ,
    MHIS.ABNUM AS "Call Number",
    TO_CHAR(NULL) AS "Package",
    TO_CHAR(NULL) AS "Package Text",
    MPOS.EQUNR AS "Equipment Number",
    ILOA.ILOAN,
    ILOA.EQFNR AS "Sort Field",
    ILOA.TPLNR AS "FLOC",
    IFLOTX.PLTXT AS "FLOC Text",
    CRHD.ARBPL AS "Work Center",
    PLPO.LTXA1 AS "Operation Description",
    PLPO.ANZZL AS "Capacity",
    PLPO.DAUNO AS "Work",
    PLPO.ARBEI AS "Total Work Estimate",
    PLPO.ARBEH AS "Unit for Work"
    
    ,(
        SELECT
            LISTAGG(TJ30T.TXT04, ' ') WITHIN GROUP (ORDER BY TJ30T.TXT04)
        FROM JEST
        JOIN JSTO ON JSTO.OBJNR = JEST.OBJNR
        JOIN TJ30T ON JSTO.STSMA = TJ30T.STSMA AND JEST.STAT = TJ30T.ESTAT
        WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ30T.SPRAS = 'E'
    ) AS "User Status"
    ,(
        SELECT
            LISTAGG(TJ02T.TXT04, ' ') WITHIN GROUP (ORDER BY TJ02T.TXT04)
        FROM JEST
        JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
        WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
    ) AS "System Status"
    /*,(
        SELECT
            LISTAGG(TJ02T.TXT04, ' ') WITHIN GROUP (ORDER BY TJ02T.TXT04)
        FROM JEST
        JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
        WHERE JEST.OBJNR = AFVC.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
    ) AS "Opperation System Status"
    */
    FROM MHIS
    
    JOIN MPLA ON MPLA.WARPL = MHIS.WARPL AND LENGTH(MPLA.STRAT) = 1
    LEFT JOIN MPOS ON MPOS.WARPL = MHIS.WARPL
    LEFT JOIN PLKO ON MPOS.PLNNR = PLKO.PLNNR AND MPOS.PLNAL = PLKO.PLNAL
    LEFT JOIN PLAS ON PLAS.PLNNR = PLKO.PLNNR AND PLAS.PLNAL = PLKO.PLNAL AND PLAS.PLNTY = 'A' AND PLAS.LOEKZ <> 'X'
    LEFT JOIN PLPO ON PLPO.PLNTY = PLAS.PLNTY AND PLPO.PLNNR = PLAS.PLNNR AND PLPO.PLNKN = PLAS.PLNKN AND PLPO.ZAEHL = PLAS.ZAEHL
    LEFT JOIN ILOA ON ILOA.ILOAN = MPOS.ILOAN
    LEFT JOIN IFLOTX ON IFLOTX.TPLNR = ILOA.TPLNR
    LEFT JOIN CRHD ON CRHD.OBJID = MPOS.GEWRK
    LEFT JOIN CRHD op ON op.OBJID = PLPO.ARBID
    LEFT JOIN AFIH ON AFIH.WARPL = MPOS.WARPL AND AFIH.WAPOS = MPOS.WAPOS AND AFIH.ABNUM = MHIS.ABNUM
    LEFT JOIN AFKO ON AFKO.AUFNR = AFIH.AUFNR
    LEFT JOIN AUFK ON AFIH.AUFNR = AUFK.AUFNR
    LEFT JOIN AFVC ON AFVC.AUFPL = AFKO.AUFPL AND AFVC.VORNR = PLPO.VORNR
    LEFT JOIN AFVV ON AFVV.AUFPL = AFVC.AUFPL AND AFVV.APLZL = AFVC.APLZL
    
    WHERE (MHIS.NPLDA >= 20171113 AND MHIS.NPLDA <= 20171119)
    AND 
(
    NOT EXISTS (
        SELECT TJ02T.TXT04
        FROM JEST
        JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
        WHERE JEST.OBJNR = MPLA.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
        AND TJ02T.TXT04 IN ('INAC', 'DLFL')
    )
)
    ;