define startDate = '20181002'
define endDate = '20181002'

SELECT
    CASE 
        WHEN op.ARBPL LIKE 'TAB%' THEN 'FMT'
        WHEN op.ARBPL LIKE 'FMG%' THEN 'FMT'
        WHEN op.ARBPL LIKE 'MIC%' THEN 'CMT'
        WHEN op.ARBPL LIKE 'IC' THEN 'IC'
        WHEN op.ARBPL LIKE 'WTR%' THEN 'UPW'
        WHEN op.ARBPL LIKE 'ELEC%' THEN 'ELEC'
        WHEN op.ARBPL LIKE 'GAS%' THEN 'GAS'
        WHEN op.ARBPL LIKE 'CHEM%' THEN 'CHEM'
        WHEN op.ARBPL LIKE 'SLUR%' THEN 'SLURRY'
        WHEN op.ARBPL LIKE 'ALOP%' THEN 'AL OP'
        WHEN op.ARBPL LIKE 'TGM' THEN 'TGM'
        WHEN op.ARBPL LIKE 'BS' THEN 'BS'
        ELSE op.ARBPL
        END AS "Op Work Center"
    ,AUFK.AUART AS "Order Type"
    ,COUNT(CASE WHEN AFKO.GSTRP BETWEEN &startDate AND &endDate /*AND (AFKO.GETRI = '00000000' OR AFKO.GETRI = ' ' OR AFKO.GETRI BETWEEN &startDate AND &endDate)*/ AND AFIH.IWERK = '8000' AND AUFK.AUART IN ('8F06','8F03','8F02','8F01') THEN 1 END) AS "Planned Tasks"
    ,SUM(CASE WHEN AFKO.GSTRP BETWEEN &startDate AND &endDate /*AND (AFKO.GETRI = '00000000' OR AFKO.GETRI = ' ' OR AFKO.GETRI BETWEEN &startDate AND &endDate)*/ AND AFIH.IWERK = '8000' AND AUFK.AUART IN ('8F06','8F03','8F02','8F01') THEN AFVV.ARBEI END) AS "Planned Work"
    ,COUNT(CASE WHEN AFKO.GETRI BETWEEN &startDate AND &endDate AND AFIH.IWERK = '8000' AND AUFK.AUART IN ('8F06','8F03','8F02','8F01') THEN 1 END) AS "Completed Tasks"
    ,SUM(CASE WHEN AFKO.GETRI BETWEEN &startDate AND &endDate AND AFIH.IWERK = '8000' AND AUFK.AUART IN ('8F06','8F03','8F02','8F01') THEN AFVV.ISMNW END) AS "Total Planned Work"
    --,SUM(CASE WHEN AFRU.ERSDA BETWEEN &startDate AND &endDate AND AFIH.IWERK = '8000' AND AUFK.AUART IN ('8F06','8F03','8F02','8F01') THEN CASE AFRU.STOKZ WHEN 'X' THEN AFRU.ISMNW * -1 ELSE AFRU.ISMNW END END) AS "Entered Work"
    
    ,COUNT(
            CASE WHEN (AFKO.GSTRP BETWEEN &startDate AND &endDate 
            AND AFKO.GETRI BETWEEN &startDate AND &endDate)
            AND AFKO.GSTRP = AFKO.GETRI
            AND AFIH.IWERK = '8000' 
            AND AUFK.AUART IN ('8F06','8F03','8F02','8F01') THEN 1
        END) AS "PvA Tasks"
    --,SUM(CASE WHEN AFRU.ERSDA BETWEEN &startDate AND &endDate THEN AFRU.ISMNW END) AS "Entered Work"
    /*
    ,(
        SELECT
			SUM(CASE AB.STOKZ WHEN 'X' THEN AB.ISMNW * -1 ELSE AB.ISMNW END)
        FROM AFRU AB
        JOIN AFVC AC ON AC.RUECK = AB.RUECK AND AC.RMZHL = AB.RMZHL
        JOIN AFKO AD ON AD.AUFPL = AC.AUFPL
        JOIN AUFK A ON A.AUFNR = AD.AUFNR
        JOIN AFIH AF ON AF.AUFNR = A.AUFNR
		--FROM AFRU
		--JOIN AFVC ON AFVC.RUECK = AFRU.RUECK AND AFVC.RMZHL = AFRU.RMZHL
        --JOIN AFKO ON AFVC.AUFPL = AFKO.AUFPL
        WHERE AB.ERSDA BETWEEN &startDate AND &endDate
        AND AFIH.AUFNR = AF.AUFNR
    ) AS "Total Entered"
    */
    
    --,SUM(CASE WHEN AFKO.GSTRP BETWEEN &startDate AND &endDate AND AFKO.GETRI BETWEEN &startDate AND &endDate AND AFIH.IWERK = '8000' AND AUFK.AUART IN ('8F06','8F03','8F02','8F01') THEN AFVV.ISMNW END) AS "PvA Work"

    FROM AFIH

    JOIN AFKO ON AFKO.AUFNR = AFIH.AUFNR
    JOIN AUFK ON AUFK.AUFNR = AFIH.AUFNR
    JOIN AFVC ON AFVC.AUFPL = AFKO.AUFPL
    JOIN AFVV ON AFVV.AUFPL = AFVC.AUFPL AND AFVV.APLZL = AFVC.APLZL
    --FULL OUTER JOIN AFRU ON AFVC.RUECK = AFRU.RUECK
    --FULL OUTER JOIN EQKT ON EQKT.EQUNR = AFIH.EQUNR
    --FULL OUTER JOIN ILOA ON ILOA.ILOAN = AFIH.ILOAN
    --JOIN IFLOTX ON IFLOTX.TPLNR = ILOA.TPLNR
    LEFT JOIN CRHD op ON op.OBJID = AFVC.ARBID
    
    
    
    --WHERE AFKO.GSTRP = '20180913'
    WHERE AUFK.AUART IN ('8F06','8F03','8F02','8F01')
    --AND (AFKO.GETRI = '00000000' OR AFKO.GETRI = ' ' OR AFKO.GETRI = '20180913')
    AND AFIH.IWERK = '8000'
    
    GROUP BY
    CASE 
        WHEN op.ARBPL LIKE 'TAB%' THEN 'FMT'
        WHEN op.ARBPL LIKE 'FMG%' THEN 'FMT'
        WHEN op.ARBPL LIKE 'MIC%' THEN 'CMT'
        WHEN op.ARBPL LIKE 'IC' THEN 'IC'
        WHEN op.ARBPL LIKE 'WTR%' THEN 'UPW'
        WHEN op.ARBPL LIKE 'ELEC%' THEN 'ELEC'
        WHEN op.ARBPL LIKE 'GAS%' THEN 'GAS'
        WHEN op.ARBPL LIKE 'CHEM%' THEN 'CHEM'
        WHEN op.ARBPL LIKE 'SLUR%' THEN 'SLURRY'
        WHEN op.ARBPL LIKE 'ALOP%' THEN 'AL OP'
        WHEN op.ARBPL LIKE 'TGM' THEN 'TGM'
        WHEN op.ARBPL LIKE 'BS' THEN 'BS'
        ELSE op.ARBPL END
    , AUFK.AUART
    
    ORDER BY CASE 
        WHEN op.ARBPL LIKE 'TAB%' THEN 'FMT'
        WHEN op.ARBPL LIKE 'FMG%' THEN 'FMT'
        WHEN op.ARBPL LIKE 'MIC%' THEN 'CMT'
        WHEN op.ARBPL LIKE 'IC' THEN 'IC'
        WHEN op.ARBPL LIKE 'WTR%' THEN 'UPW'
        WHEN op.ARBPL LIKE 'ELEC%' THEN 'ELEC'
        WHEN op.ARBPL LIKE 'GAS%' THEN 'GAS'
        WHEN op.ARBPL LIKE 'CHEM%' THEN 'CHEM'
        WHEN op.ARBPL LIKE 'SLUR%' THEN 'SLURRY'
        WHEN op.ARBPL LIKE 'ALOP%' THEN 'AL OP'
        WHEN op.ARBPL LIKE 'TGM' THEN 'TGM'
        WHEN op.ARBPL LIKE 'BS' THEN 'BS'
        ELSE op.ARBPL END
    ;