define startDate = '20180913'
define endDate = '20180913'

SELECT
    CASE 
        WHEN op.ARBPL LIKE 'TAB%' THEN 'FMT'
        WHEN op.ARBPL LIKE 'FMG%' THEN 'FMT'
        WHEN op.ARBPL LIKE 'MIC%' THEN 'CMT'
        WHEN op.ARBPL LIKE 'IC' THEN 'IC'
        WHEN op.ARBPL LIKE 'WTR%' THEN 'UPW'
        WHEN op.ARBPL LIKE 'ELEC%' THEN 'ELEC'
        WHEN op.ARBPL LIKE 'GAS%' THEN 'GAS'
        WHEN op.ARBPL LIKE 'CHEM%' THEN 'CHEM'
        WHEN op.ARBPL LIKE 'SLUR%' THEN 'SLURRY'
        WHEN op.ARBPL LIKE 'ALOP%' THEN 'AL OP'
        WHEN op.ARBPL LIKE 'TGM' THEN 'TGM'
        WHEN op.ARBPL LIKE 'BS' THEN 'BS'
        ELSE op.ARBPL
        END AS "Op Work Center"
    ,AFIH.AUFNR AS "order"
    ,AUFK.AUART AS "Order Type"
    ,AFRU.ISMNW

    FROM AFIH

    JOIN AFKO ON AFKO.AUFNR = AFIH.AUFNR
    JOIN AUFK ON AUFK.AUFNR = AFIH.AUFNR
    JOIN AFVC ON AFVC.AUFPL = AFKO.AUFPL
    JOIN AFVV ON AFVV.AUFPL = AFVC.AUFPL AND AFVV.APLZL = AFVC.APLZL
    FULL OUTER JOIN AFRU ON AFVC.RUECK = AFRU.RUECK
    LEFT JOIN CRHD op ON op.OBJID = AFVC.ARBID
    
    WHERE AFKO.GSTRP BETWEEN '20180913' AND '20180913'
    AND AUFK.AUART IN ('8F03')
    --AND (AFKO.GETRI = '00000000' OR AFKO.GETRI = ' ' OR AFKO.GETRI = '20180913')
    AND AFIH.IWERK = '8000'
    AND op.ARBPL = 'TAB_P'

    ORDER BY CASE 
        WHEN op.ARBPL LIKE 'TAB%' THEN 'FMT'
        WHEN op.ARBPL LIKE 'FMG%' THEN 'FMT'
        WHEN op.ARBPL LIKE 'MIC%' THEN 'CMT'
        WHEN op.ARBPL LIKE 'IC' THEN 'IC'
        WHEN op.ARBPL LIKE 'WTR%' THEN 'UPW'
        WHEN op.ARBPL LIKE 'ELEC%' THEN 'ELEC'
        WHEN op.ARBPL LIKE 'GAS%' THEN 'GAS'
        WHEN op.ARBPL LIKE 'CHEM%' THEN 'CHEM'
        WHEN op.ARBPL LIKE 'SLUR%' THEN 'SLURRY'
        WHEN op.ARBPL LIKE 'ALOP%' THEN 'AL OP'
        WHEN op.ARBPL LIKE 'TGM' THEN 'TGM'
        WHEN op.ARBPL LIKE 'BS' THEN 'BS'
        ELSE op.ARBPL END
    ;