SELECT
    TO_CHAR(TO_DATE(AFRU.IEDD, 'YYYYMMDD'), 'YYYY-MM') AS "date"
    ,ROUND(SUM(CASE AFRU.ISMNE 
        WHEN 'H' THEN AFRU.ISMNW
        WHEN 'HR' THEN AFRU.ISMNW
        WHEN 'STD' THEN AFRU.ISMNW
        WHEN 'MIN' THEN AFRU.ISMNW / 60
        END), 2) AS "time"
FROM AFRU

WHERE AFRU.WERKS = '8000'

GROUP BY TO_CHAR(TO_DATE(AFRU.IEDD, 'YYYYMMDD'), 'YYYY-MM')

ORDER BY TO_CHAR(TO_DATE(AFRU.IEDD, 'YYYYMMDD'), 'YYYY-MM')
;