SELECT
	--AFRU.RUECK AS "Confirmation Link",
    --AFIH.AUFNR AS "work_order"
	AUFK.AUART AS "order_type"
	,SUM(CASE AFRU.STOKZ WHEN 'X' THEN AFRU.ISMNW * -1 ELSE AFRU.ISMNW END) AS "actual_work"
    ,CRHD.ARBPL AS "work_center"

FROM AFRU
JOIN AFVC ON AFVC.RUECK = AFRU.RUECK
JOIN AFKO ON AFKO.AUFPL = AFVC.AUFPL
JOIN AUFK ON AUFK.AUFNR = AFKO.AUFNR
JOIN AFIH ON AFIH.AUFNR = AUFK.AUFNR
JOIN AFVV ON AFVV.AUFPL = AFVC.AUFPL AND AFVV.APLZL = AFVC.APLZL
JOIN CRHD ON CRHD.OBJID = AFRU.ARBID

WHERE AFRU.ERSDA BETWEEN '20180930' AND '20181006'
AND AUFK.AUART IN ('8F01', '8F02', '8F03', '8F06')

GROUP BY CRHD.ARBPL, AUFK.AUART
ORDER BY CRHD.ARBPL

--AND AFIH.WARPL = '100000002299' AND AFIH.WAPOS = '0000000000004710'
--AND AFIH.AUFNR = '000800355622'
--AND CRHD.ARBPL = 'ELEC_P'
--AND AFRU.IEDD != AFRU.ERSDA
;