SELECT * FROM (
SELECT
    MHIS.WARPL AS "Maintenance Plan",
    MPOS.AUART AS "Order Type",
    ROUND(MHIS.ZYKZT / 3600 / 24, 2) AS "Cycle",
    AFIH.AUFNR AS "Work Order",
    CRHD.ARBPL AS "Work Center",
    --MPLA.HORIZ AS "Horizon",
    CASE MHIS.NPLDA WHEN '00000000' THEN NULL WHEN ' ' THEN NULL WHEN NULL THEN NULL ELSE TO_CHAR(TO_DATE(MHIS.NPLDA, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Planned Date",
    CASE MHIS.HORDA WHEN '00000000' THEN NULL WHEN ' ' THEN NULL WHEN NULL THEN NULL ELSE TO_CHAR(TO_DATE(MHIS.HORDA, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Call Date",
    CASE AFKO.GSTRP WHEN '00000000' THEN NULL WHEN ' ' THEN NULL WHEN NULL THEN NULL ELSE TO_CHAR(TO_DATE(AFKO.GSTRP, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Basic Start Date",
    CASE AFKO.GLTRP WHEN '00000000' THEN NULL WHEN ' ' THEN NULL WHEN NULL THEN NULL ELSE TO_CHAR(TO_DATE(AFKO.GLTRP, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Basic Finish Date",
    CASE AFKO.GETRI WHEN '00000000' THEN NULL WHEN ' ' THEN NULL WHEN NULL THEN NULL ELSE TO_CHAR(TO_DATE(AFKO.GETRI, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Confirmed Finish Date",
    --MPLA.CALL_CONFIRM AS "Completion Required",
    --MPOS.NO_AUFRELKZ AS "No Auto Release",
    --MPLA.ABRHO AS "Scheduling Period",
    --CASE WHEN MPLA.HUNIT = '10' THEN 'Days' ELSE 'Years' END AS "Scheduling Period Unit",
    MPLA.WPTXT AS "Maintenance Plan Text",
    MPOS.PSTXT AS "Maintenance Item Text",
    MPLA.STRAT AS "Maintenance Strategy",
    MHIS.ABNUM AS "Call Number",
    TO_CHAR(NULL) AS "Package",
    TO_CHAR(NULL) AS "Package Text",
    MPOS.EQUNR AS "Equipment Number",
    ILOA.EQFNR AS "Sort Field",
    ILOA.TPLNR AS "FLOC",
    IFLOTX.PLTXT AS "FLOC Text",
    null AS "User Status",
    null AS "System Status"
    
    FROM MHIS
    
    JOIN MPLA ON MPLA.WARPL = MHIS.WARPL AND LENGTH(MPLA.STRAT) = 1
    LEFT JOIN MPOS ON MPOS.WARPL = MHIS.WARPL
    LEFT JOIN ILOA ON ILOA.ILOAN = MPOS.ILOAN
    LEFT JOIN IFLOTX ON IFLOTX.TPLNR = ILOA.TPLNR
    LEFT JOIN CRHD ON CRHD.OBJID = MPOS.GEWRK
    LEFT JOIN AFIH ON AFIH.WARPL = MPOS.WARPL AND AFIH.WAPOS = MPOS.WAPOS AND AFIH.ABNUM = MHIS.ABNUM
    LEFT JOIN AFKO ON AFKO.AUFNR = AFIH.AUFNR
    LEFT JOIN AUFK ON AFIH.AUFNR = AUFK.AUFNR

    WHERE
(
    NOT EXISTS (
        SELECT TJ02T.TXT04
        FROM JEST
        JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
        WHERE JEST.OBJNR = MPLA.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
        AND TJ02T.TXT04 IN ('INAC', 'DLFL')
    )
)
    AND MHIS.NPLDA BETWEEN '20180916' AND '20180922'
    AND AFIH.AUFNR IS NULL
UNION ALL
SELECT
    MHIS.WARPL AS "Maintenance Plan",
    MPOS.AUART AS "Order Type",
    ROUND(MHIS.ZYKZT / 3600 / 24, 2) AS "Cycle",
    AFIH.AUFNR AS "Work Order",
    CRHD.ARBPL AS "Work Center",
    --MPLA.HORIZ AS "Horizon",
    CASE MHIS.NPLDA WHEN '00000000' THEN NULL WHEN ' ' THEN NULL WHEN NULL THEN NULL ELSE TO_CHAR(TO_DATE(MHIS.NPLDA, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Planned Date",
    CASE MHIS.HORDA WHEN '00000000' THEN NULL WHEN ' ' THEN NULL WHEN NULL THEN NULL ELSE TO_CHAR(TO_DATE(MHIS.HORDA, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Call Date",
    CASE AFKO.GSTRP WHEN '00000000' THEN NULL WHEN ' ' THEN NULL WHEN NULL THEN NULL ELSE TO_CHAR(TO_DATE(AFKO.GSTRP, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Basic Start Date",
    CASE AFKO.GLTRP WHEN '00000000' THEN NULL WHEN ' ' THEN NULL WHEN NULL THEN NULL ELSE TO_CHAR(TO_DATE(AFKO.GLTRP, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Basic Finish Date",
    CASE AFKO.GETRI WHEN '00000000' THEN NULL WHEN ' ' THEN NULL WHEN NULL THEN NULL ELSE TO_CHAR(TO_DATE(AFKO.GETRI, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Confirmed Finish Date",
    --MPLA.CALL_CONFIRM AS "Completion Required",
    --MPOS.NO_AUFRELKZ AS "No Auto Release",
    --MPLA.ABRHO AS "Scheduling Period",
   -- CASE WHEN MPLA.HUNIT = '10' THEN 'Days' ELSE 'Years' END AS "Scheduling Period Unit",
    MPLA.WPTXT AS "Maintenance Plan Text",
    MPOS.PSTXT AS "Maintenance Item Text",
    MPLA.STRAT AS "Maintenance Strategy",
    MHIS.ABNUM AS "Call Number",
    T351X.PAKET AS "Package",
    T351X.KTEX1 AS "Package Text",
    MPOS.EQUNR AS "Equipment Number",
    ILOA.EQFNR AS "Sort Field",
    ILOA.TPLNR AS "FLOC",
    IFLOTX.PLTXT AS "FLOC Text",
    null AS "User Status",
    null AS "System Status"

    FROM MHIS
    
	JOIN MPLA ON MHIS.WARPL = MPLA.WARPL AND LENGTH(MPLA.STRAT) > 1
	INNER JOIN MPOS ON MPOS.WARPL = MHIS.WARPL
	LEFT JOIN T351X ON T351X.STRAT = MPLA.STRAT AND T351X.PAKET = MHIS.ZAEHL
	LEFT JOIN CRHD ON CRHD.OBJID = MPOS.GEWRK
	LEFT JOIN ILOA ON ILOA.ILOAN = MPOS.ILOAN
	LEFT JOIN IFLOTX ON IFLOTX.TPLNR = ILOA.TPLNR
	LEFT JOIN AFIH ON AFIH.WARPL = MPOS.WARPL AND AFIH.WAPOS = MPOS.WAPOS AND AFIH.ABNUM = MHIS.ABNUM
	LEFT JOIN AFKO ON AFKO.AUFNR = AFIH.AUFNR
	LEFT JOIN AUFK ON AFIH.AUFNR = AUFK.AUFNR
    
    WHERE 
(
    NOT EXISTS (
        SELECT TJ02T.TXT04
        FROM JEST
        JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
        WHERE JEST.OBJNR = MPLA.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
        AND TJ02T.TXT04 IN ('INAC', 'DLFL')
    )
)
    AND MHIS.NPLDA BETWEEN '20180916' AND '20180922'
    AND AFIH.AUFNR IS NULL
UNION ALL
SELECT
    AFIH.WARPL AS "Maintenance Plan",
    AUFK.AUART AS "Order Type",
    A."Cycle",
    AFIH.AUFNR AS "Work Order",
    AUFK.VAPLZ AS "Work Center",
    --TO_CHAR(NULL) AS "Horizon",
    CASE A.NPLDA WHEN '00000000' THEN NULL WHEN ' ' THEN NULL WHEN NULL THEN NULL ELSE TO_CHAR(TO_DATE(A.NPLDA, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Planned Date",
    CASE AUFK.ERDAT WHEN '00000000' THEN NULL WHEN ' ' THEN NULL WHEN NULL THEN NULL ELSE TO_CHAR(TO_DATE(AUFK.ERDAT, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Call Date",
    CASE AFKO.GSTRP WHEN '00000000' THEN NULL WHEN ' ' THEN NULL WHEN NULL THEN NULL ELSE TO_CHAR(TO_DATE(AFKO.GSTRP, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Basic Start Date",
    CASE AFKO.GLTRP WHEN '00000000' THEN NULL WHEN ' ' THEN NULL WHEN NULL THEN NULL ELSE TO_CHAR(TO_DATE(AFKO.GLTRP, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Basic Finish Date",
    CASE AFKO.GETRI WHEN '00000000' THEN NULL WHEN ' ' THEN NULL WHEN NULL THEN NULL ELSE TO_CHAR(TO_DATE(AFKO.GETRI, 'YYYYMMDD'), 'YYYY-MM-DD') END AS "Confirmed Finish Date",
    --TO_CHAR(NULL) AS "Completion Required",
    --TO_CHAR(NULL) AS "No Auto Release",
    --TO_CHAR(NULL) AS "Scheduling Period",
    --TO_CHAR(NULL) AS "Scheduling Period Unit",
    TO_CHAR(NULL) AS "Maintenance Plan Text",
    AUFK.KTEXT AS "Maintenance Item Text",
    TO_CHAR(NULL) AS "Maintenance Strategy",
    NULL AS "Call Number",
    TO_CHAR(NULL) AS "Package",
    TO_CHAR(NULL) AS "Package Text",
    TO_CHAR(NULL) AS "Equipment Number",
    ILOA.EQFNR AS "Sort Field",
    ILOA.TPLNR AS "FLOC",
    IFLOTX.PLTXT AS "FLOC Text"
    , (
        SELECT
			LISTAGG(TJ30T.TXT04, ' ') WITHIN GROUP (ORDER BY TJ30T.TXT04)
		FROM JEST
		JOIN JSTO ON JSTO.OBJNR = JEST.OBJNR
		JOIN TJ30T ON JSTO.STSMA = TJ30T.STSMA AND JEST.STAT = TJ30T.ESTAT
		WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ30T.SPRAS = 'E'
    ) AS "User Status"
    ,(
        SELECT
			LISTAGG(TJ02T.TXT04, ' ') WITHIN GROUP (ORDER BY TJ02T.TXT04)
		FROM JEST
		JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT
		WHERE JEST.OBJNR = AUFK.OBJNR AND JEST.INACT != 'X' AND TJ02T.SPRAS = 'E'
    ) AS "System Status"

    FROM AFIH

    JOIN AFKO ON AFKO.AUFNR = AFIH.AUFNR
    JOIN AUFK ON AUFK.AUFNR = AFIH.AUFNR
    FULL OUTER JOIN EQKT ON EQKT.EQUNR = AFIH.EQUNR
    FULL OUTER JOIN ILOA ON ILOA.ILOAN = AFIH.ILOAN
    JOIN IFLOTX ON IFLOTX.TPLNR = ILOA.TPLNR
    
    FULL OUTER JOIN (
    SELECT
        WARPL
        ,NPLDA
        ,ABNUM
        ,MAX(ROUND(ZYKZT / 3600 / 24, 2)) AS "Cycle"
    FROM MHIS
    GROUP BY WARPL, NPLDA, ABNUM
    ) A ON A.WARPL = AFIH.WARPL AND A.ABNUM = AFIH.ABNUM
    
    WHERE AFKO.GSTRP BETWEEN '20180923' AND '20180929'
)
WHERE --(
    --"Planned Date" BETWEEN '2018-09-16' AND '2018-09-22'
    --OR 
    --"Basic Finish Date" BETWEEN '2018-09-16' AND '2018-09-22'
    --)
--WHERE "Maintenance Plan" = '100000001168'
"Confirmed Finish Date" IS NULL
AND "Order Type" IN ('8F03','8F02','8F01')

--AND "Work Order" IS NULL
--AND ("Work Center" IN ('FMG_P', 'TAB_P') OR "Op Work Center" IN ('FMG_P', 'TAB_P'))
/*
WHERE "Work Order" IN (
  '000800236078',
  '000800237220',
  '000800236544',
  '000800237623',
  '000800236566',
  '000800239270',
  '000800238785'
)
*/
;